### ISSUE TITLE
Import Bootstrap 4

### ISSUE THREAD

**Issue by stephencarico** [codefordenver/codefordenver.org#127]
## Reasons why we should use Bootstrap
*(or any easy-to-learn CSS library)*
  + Reduces CSS conflicts and duplicated code that comes from a team of developers writing CSS in isolated files.
  + Leads to MUCH faster development and less coding
  + Responsiveness already baked in
  + Establishes a consistent feel and follows professional guidelines
  + Helps teach new developers how to work with a CSS library
  + VERY lightweight - simply a bundle of SCSS files that are simply copied and pasted
  + Does not have any noticeable build slowdown

**Comment by stephencarico** [comment]
After speaking with Ryan we will be putting a pause on this import. The design is pretty simple and bootstrap may be overkill. Let's see if we can do this bare HTML / CSS. If this becomes too much of a challenge this is when we can merge this branch (i.e. import Botostrap)

**Comment by rhynobytes** [comment]
Closing PR. Will not merge
