### ISSUE TITLE
Add Meetup plugin

### ISSUE THREAD

**Issue by LuckyLimey** [codefordenver/codefordenver.org#4]
https://wordpress.org/plugins/wp-meetup/

**Comment by LuckyLimey** [comment]
Description

Meetup is used by 9.5 million members who meet over 2,000 times every single day in local communities across the nation. Unfortunately, there hasn’t been an efficient way to link an organization’s Meetup events easily and efficiently to their WordPress site.

Until now.

Nuanced Media’s WP Meetup plugin fetches event information from Meetup.com and creates posts for each event. WP Meetup also provides an event calendar for displaying events, either on a page or as a widget.

New in version 2.0!

• Display multiple groups on one calendar, each group with their own color highlight. Perfect for organizers of multiple, related groups!
• Display multiple months of events, including past, present, and future events. Help your members plan ahead for special events!
• Calendar widget that displays a small calendar in the widget area, as well as a new widget that lists seven upcoming events.
• Increased database stability for calendar creation.

It has never been so easy to aggregate and display events.

For more information, visit the plugin homepage at Nuanced Media.

**Comment by dviramontes** [comment]
@2kIQ yes totally, thanks!
