### ISSUE TITLE
WP Event Aggregator: Import Facebook, Eventbrite, Meetup, iCal Events

### ISSUE THREAD

**Issue by LuckyLimey** [codefordenver/codefordenver.org#5]

**Comment by 2kIQ** [comment]
Just FYI, the entire The Events Calendar suite appears to be free for not for profits...

**Comment by cwmcallister** [comment]
After significant research, there is no free plugin that will pull an iCal feed on a regular basis.
There are a few paid options out there that may offer discounts to non-profits, but I haven't found any explicit non-profit offers.

While The Events Calendar offers a pro version to non-profits, we would still need the Event Aggregator add-on to take advantage of the options.

Has anyone else dug deep into this?
I'm not sure what the difficulty level of building our own plugin is, maybe that's an option?

**Comment by LuckyLimey** [comment]
Have you looked at a WebDAV solution.? Works with ical and is "open
standard". ...

**Comment by LuckyLimey** [comment]
I would use WebDAV and suck everything into Google Calendar... Or even dump
iCal all together... Apple cloud is notoriously bad...  Appleinsider.com
has a good discussion iCal vs Google calendar s.

On Apr 2, 2018 8:07 PM, "cwmcallister" <notifications@github.com> wrote:

After significant research, there is no free plugin that will pull an iCal
feed on a regular basis.
There are a few paid options out there that may offer discounts to
non-profits, but I haven't found any explicit non-profit offers.

While The Events Calendar offers a pro version to non-profits, we would
still need the Event Aggregator add-on to take advantage of the options.

Has anyone else dug deep into this?
I'm not sure what the difficulty level of building our own plugin is, maybe
that's an option?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/codefordenver/codefordenver.org/issues/5#issuecomment-378104600>,
or mute the thread
