### ISSUE TITLE
Handle newsletter email submission on the homepage

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/codefordenver.org#63]
<img width="578" alt="Screen Shot 2019-09-05 at 9 03 07 PM" src="https://user-images.githubusercontent.com/144226/64398033-9cd13d00-d020-11e9-80a3-b0676069dbc2.png">

**Comment by rhynobytes** [comment]
@dviramontes is this list being managed on MailChimp?

**Comment by dviramontes** [comment]
I believe so yes.
