### ISSUE TITLE
Replace galvanize with workability

### ISSUE THREAD

**Issue by anotherpatrickcollins** [codefordenver/codefordenver.org#93]
Replace galvanize logo with workability logo.

- on homepage https://codefordenver.org/
- on about page https://codefordenver.org/about

![Workability Logo_sm](https://user-images.githubusercontent.com/17071865/66959480-b0ac8d80-f027-11e9-9e8e-b4df7def664e.jpg)
![Workability Logo](https://user-images.githubusercontent.com/17071865/66959481-b1452400-f027-11e9-883c-c5969cfc71f8.jpg)

**Comment by dhausk** [comment]
pull request merged
